# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: <domain>/<namespace>/<app-name>
  tag: 1.0.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
service:
  name: node
  type: ClusterIP
  servicePort: 3000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
base:
  enabled: false
  replicaCount: 1
  image:
    tag: v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
