openapi: '3.0.0'

info:
  version: "1.0.0"
  title: REST API app
  
servers: 
  - url: http://localhost:3000
  
paths:
  /:
    get:
      description: Hello world path
      responses:
        200:
          description: Hello World
          content:
            text:
              example: 
                text: "Hello World!"

  /health:
    get:
      operationId: getHealth
      tags:
        - Health
      description: Get health status of app 
      responses:
        200:
          description: Health check response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example: 
                application/json: { "success": "true", "message": "Server is up!", "status": "UP" }

  /ping:
    get:
      operationId: pingCC
      tags:
        - Ping
      description: Ping blockchain network
      responses:
        200:
          description: Ping response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
            
  /securedPing:
    get:
      operationId: getSecured
      tags:
        - Secured
      description: Get status of app after authenticating
      security: #this is not at root level in yaml because only this route is secured/needs auth token
      - BearerAuth: []
      responses:
        200:
          description: Secured route response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecuredResponse'

components:
  securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT 
  schemas:
    ResponseBody:
      properties:
        success:
          type: boolean
        message: 
          type: string
          
    HealthResponse:
      allOf:  
        - $ref: '#/components/schemas/ResponseBody'
        - type: object
          properties:
            success:
              type: boolean
            message: 
              type: string
              
    SecuredResponse:
      allOf:  
        - $ref: '#/components/schemas/ResponseBody'
        - type: object
          properties:
            status:
              type: string

